seed: 23

# Model parameters
model: "LiquidAI/LFM2-VL-450M"
structured_generation: false

# Dataset parameters
dataset: "microsoft/cats_vs_dogs"
n_samples: 100

system_prompt: |
  You are a veterinarian specialized in analyzing pictures of cats and dogs
  You excel at identifying the type of animal from a picture and its breed.

user_prompt: |
  What animal and breed do you see in this image?

  Provide your final JSON response without any additional text or formatting.

  Example output 1:
  {
    "animal": "dog",
    "breed": "Labrador"
  }

  Example output 2:
  {
    "animal": "cat",
    "breed": "Siamese"
  }

  Example output 3:
  {
    "animal": "other",
  }

image_column: "image"
label_column: "labels"
label_mapping:
  0: "cat"
  1: "dog"